version: '3.8'

services:
  tiny-url:
    build: .
    container_name: tiny-url-app
    ports:
      - "8000:8000"
    volumes:
      - ./:/app  # Mount current dir to /app inside container (for dev)
    working_dir: /app
    command: uvicorn kgs.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - AWS_ACCESS_KEY_ID=your-access-key
      - AWS_SECRET_ACCESS_KEY=your-secret-key
      - AWS_DEFAULT_REGION=us-east-1